title: Carlos Estrada
permalink: /:slug

sass:
  style: compressed

social:
  twitter: https://twitter.com/cestrrada
  github: https://github.com/cestrrada
  behance: https://behance.net/cestrrada
  linkedin: https://linkedin.com/in/cestrrada
  email: mailto:cestrrada@gmail.com
  
collections:
  projects:
    permalink: /:slug
    output: true