title: Carlos Estrada
logo: /resources/img/site/logo.svg
permalink: /:slug

# Social media links
social:
  - name: Twitter
    icon: fab fa-twitter
    url: https://twitter.com/cestrrada
  - name: GitHub
    icon: fab fa-github
    url: https://github.com/cestrrada
  - name: Behance
    icon: fab fa-behance
    url: https://behance.net/cestrrada
  - name: LinkedIn
    icon: fab fa-linkedin-in
    url: https://linkedin.com/in/cestrrada
  - name: Email
    icon: fas fa-envelope
    url: mailto:cestrrada@gmail.com

# Projects
collections:
  projects:
    permalink: /:slug
    output: true
    
assets:
  img: /assets/img/
  css: /assets/css/
  js: /assets/js/
  files: assets/files/
    
# Project Settings
sass:
  style: compressed